name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

permissions:
  id-token: write
  contents: read

concurrency:
  group: tflab-apply
  cancel-in-progress: false

env:
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  destroy:
    if: ${{ inputs.confirm == 'destroy' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.1"
      - run: terraform init
      - run: terraform plan -destroy -no-color -input=false
      - run: terraform destroy -auto-approve -input=false